var telegram={
    storires:{
        manojStory:"image",
        manojFriendstory:"videos"
    },
    chats:
        {
            uday:[
                "messeges",
                "audiochat",
                "audioCall",
                "videoCall",
                "location",
                "photos",
                "videos",
                "emoji's"
            ],
            sripad:[
                "messeges",
                "audiochat",
                "audioCall",
                "videoCall",
                "location",
                "photos",
                "videos",
                "emoji's"
            ]
        },
    channels:{
        group1:
        {
            admin:[
                "notices",
                "polls",
                "links",
                "results",
                "tasks"
            ]
        },
        group2:
        {
            admin:[
                "notices",
                "polls",
                "links",
                "results",
                "tasks"
            ]
        }    
    }
}
    

